export const data = [
    {
        _id: "66b5befb311c2c34503fdc59",
        title: "Essence Mascara Lash Princess",
        category: "beauty",
        brand: "Essence",
        price: 9.99,
        discount: 7.17,
        rating: 4.94,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc5a",
        title: "Eyeshadow Palette with Mirror",
        category: "beauty",
        brand: "Glamour Beauty",
        price: 19.99,
        discount: 5.5,
        rating: 3.28,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc5b",
        title: "Powder Canister",
        category: "beauty",
        brand: "Velvet Touch",
        price: 14.99,
        discount: 18.14,
        rating: 3.82,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc5c",
        title: "Red Lipstick",
        category: "beauty",
        brand: "Chic Cosmetics",
        price: 12.99,
        discount: 19.03,
        rating: 2.51,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/beauty/Red%20Lipstick/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc5d",
        title: "Red Nail Polish",
        category: "beauty",
        brand: "Nail Couture",
        price: 8.99,
        discount: 2.46,
        rating: 3.91,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc5e",
        title: "Calvin Klein CK One",
        category: "fragrances",
        brand: "Calvin Klein",
        price: 49.99,
        discount: 0.32,
        rating: 4.85,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc5f",
        title: "Chanel Coco Noir Eau De",
        category: "fragrances",
        brand: "Chanel",
        price: 129.99,
        discount: 18.64,
        rating: 2.76,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc60",
        title: "Dior J'adore",
        category: "fragrances",
        brand: "Dior",
        price: 89.99,
        discount: 17.44,
        rating: 3.31,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc61",
        title: "Dolce Shine Eau de",
        category: "fragrances",
        brand: "Dolce & Gabbana",
        price: 69.99,
        discount: 11.47,
        rating: 2.68,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc62",
        title: "Gucci Bloom Eau de",
        category: "fragrances",
        brand: "Gucci",
        price: 79.99,
        discount: 8.9,
        rating: 2.69,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc63",
        title: "Annibale Colombo Bed",
        category: "furniture",
        brand: "Annibale Colombo",
        price: 1899.99,
        discount: 0.29,
        rating: 4.14,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc64",
        title: "Annibale Colombo Sofa",
        category: "furniture",
        brand: "Annibale Colombo",
        price: 2499.99,
        discount: 18.54,
        rating: 3.08,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc65",
        title: "Bedside Table African Cherry",
        category: "furniture",
        brand: "Furniture Co.",
        price: 299.99,
        discount: 9.58,
        rating: 4.48,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc66",
        title: "Knoll Saarinen Executive Conference Chair",
        category: "furniture",
        brand: "Knoll",
        price: 499.99,
        discount: 15.23,
        rating: 4.11,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc67",
        title: "Wooden Bathroom Sink With Mirror",
        category: "furniture",
        brand: "Bath Trends",
        price: 799.99,
        discount: 11.22,
        rating: 3.26,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc68",
        title: "Apple",
        category: "groceries",
        brand: "other",
        price: 1.99,
        discount: 1.97,
        rating: 2.96,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Apple/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc69",
        title: "Beef Steak",
        category: "groceries",
        brand: "other",
        price: 12.99,
        discount: 17.99,
        rating: 2.83,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Beef%20Steak/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc6a",
        title: "Cat Food",
        category: "groceries",
        brand: "other",
        price: 8.99,
        discount: 9.57,
        rating: 2.88,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Cat%20Food/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc6b",
        title: "Chicken Meat",
        category: "groceries",
        brand: "other",
        price: 9.99,
        discount: 10.46,
        rating: 4.61,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Chicken%20Meat/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc6c",
        title: "Cooking Oil",
        category: "groceries",
        brand: "other",
        price: 4.99,
        discount: 18.89,
        rating: 4.01,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Cooking%20Oil/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc6d",
        title: "Cucumber",
        category: "groceries",
        brand: "other",
        price: 1.49,
        discount: 11.44,
        rating: 4.71,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Cucumber/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc6e",
        title: "Dog Food",
        category: "groceries",
        brand: "other",
        price: 10.99,
        discount: 18.15,
        rating: 2.74,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Dog%20Food/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc6f",
        title: "Eggs",
        category: "groceries",
        brand: "other",
        price: 2.99,
        discount: 5.8,
        rating: 4.46,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Eggs/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc70",
        title: "Fish Steak",
        category: "groceries",
        brand: "other",
        price: 14.99,
        discount: 7,
        rating: 4.83,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Fish%20Steak/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc71",
        title: "Green Bell Pepper",
        category: "groceries",
        brand: "other",
        price: 1.29,
        discount: 15.5,
        rating: 4.28,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Green%20Bell%20Pepper/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc72",
        title: "Green Chili Pepper",
        category: "groceries",
        brand: "other",
        price: 0.99,
        discount: 18.51,
        rating: 4.43,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Green%20Chili%20Pepper/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc73",
        title: "Honey Jar",
        category: "groceries",
        brand: "other",
        price: 6.99,
        discount: 1.91,
        rating: 3.5,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Honey%20Jar/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc74",
        title: "Ice Cream",
        category: "groceries",
        brand: "other",
        price: 5.49,
        discount: 7.58,
        rating: 3.77,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc75",
        title: "Juice",
        category: "groceries",
        brand: "other",
        price: 3.99,
        discount: 5.45,
        rating: 3.41,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Juice/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc76",
        title: "Kiwi",
        category: "groceries",
        brand: "other",
        price: 2.49,
        discount: 10.32,
        rating: 4.37,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Kiwi/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc77",
        title: "Lemon",
        category: "groceries",
        brand: "other",
        price: 0.79,
        discount: 17.81,
        rating: 4.25,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Lemon/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc78",
        title: "Milk",
        category: "groceries",
        brand: "other",
        price: 3.49,
        discount: 15.09,
        rating: 3.14,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Milk/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc79",
        title: "Mulberry",
        category: "groceries",
        brand: "other",
        price: 4.99,
        discount: 16.35,
        rating: 3.19,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Mulberry/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc7a",
        title: "Nescafe Coffee",
        category: "groceries",
        brand: "other",
        price: 7.99,
        discount: 11.65,
        rating: 2.54,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Nescafe%20Coffee/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc7b",
        title: "Potatoes",
        category: "groceries",
        brand: "other",
        price: 2.29,
        discount: 4.05,
        rating: 3.82,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Potatoes/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc7c",
        title: "Protein Powder",
        category: "groceries",
        brand: "other",
        price: 19.99,
        discount: 1.58,
        rating: 3.91,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Protein%20Powder/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc7d",
        title: "Red Onions",
        category: "groceries",
        brand: "other",
        price: 1.99,
        discount: 17.89,
        rating: 4.08,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Red%20Onions/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc7e",
        title: "Rice",
        category: "groceries",
        brand: "other",
        price: 5.99,
        discount: 12.02,
        rating: 3.94,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Rice/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc7f",
        title: "Soft Drinks",
        category: "groceries",
        brand: "other",
        price: 1.99,
        discount: 1.88,
        rating: 4.59,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Soft%20Drinks/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc80",
        title: "Strawberry",
        category: "groceries",
        brand: "other",
        price: 3.99,
        discount: 19.59,
        rating: 4.5,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Strawberry/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc81",
        title: "Tissue Paper Box",
        category: "groceries",
        brand: "other",
        price: 2.49,
        discount: 15.44,
        rating: 4.55,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Tissue%20Paper%20Box/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc82",
        title: "Water",
        category: "groceries",
        brand: "other",
        price: 0.99,
        discount: 13.71,
        rating: 2.93,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/groceries/Water/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc83",
        title: "Decoration Swing",
        category: "home-decoration",
        brand: "other",
        price: 59.99,
        discount: 0.65,
        rating: 3.56,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/home-decoration/Decoration%20Swing/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc84",
        title: "Family Tree Photo Frame",
        category: "home-decoration",
        brand: "other",
        price: 29.99,
        discount: 1.53,
        rating: 3.84,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/home-decoration/Family%20Tree%20Photo%20Frame/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc85",
        title: "House Showpiece Plant",
        category: "home-decoration",
        brand: "other",
        price: 39.99,
        discount: 19.45,
        rating: 3.61,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/home-decoration/House%20Showpiece%20Plant/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc86",
        title: "Plant Pot",
        category: "home-decoration",
        brand: "other",
        price: 14.99,
        discount: 0.19,
        rating: 3.33,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/home-decoration/Plant%20Pot/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc87",
        title: "Table Lamp",
        category: "home-decoration",
        brand: "other",
        price: 49.99,
        discount: 0.59,
        rating: 4.56,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/home-decoration/Table%20Lamp/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc88",
        title: "Bamboo Spatula",
        category: "kitchen-accessories",
        brand: "other",
        price: 7.99,
        discount: 4.85,
        rating: 4.4,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Bamboo%20Spatula/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc89",
        title: "Black Aluminium Cup",
        category: "kitchen-accessories",
        brand: "other",
        price: 5.99,
        discount: 9.22,
        rating: 3.62,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Black%20Aluminium%20Cup/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc8a",
        title: "Black Whisk",
        category: "kitchen-accessories",
        brand: "other",
        price: 9.99,
        discount: 16.87,
        rating: 2.88,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Black%20Whisk/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc8b",
        title: "Boxed Blender",
        category: "kitchen-accessories",
        brand: "other",
        price: 39.99,
        discount: 7.36,
        rating: 2.73,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Boxed%20Blender/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc8c",
        title: "Carbon Steel Wok",
        category: "kitchen-accessories",
        brand: "other",
        price: 29.99,
        discount: 5.89,
        rating: 2.94,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Carbon%20Steel%20Wok/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc8d",
        title: "Chopping Board",
        category: "kitchen-accessories",
        brand: "other",
        price: 12.99,
        discount: 17.72,
        rating: 4.82,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Chopping%20Board/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc8e",
        title: "Citrus Squeezer Yellow",
        category: "kitchen-accessories",
        brand: "other",
        price: 8.99,
        discount: 12.35,
        rating: 4.18,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Citrus%20Squeezer%20Yellow/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc8f",
        title: "Egg Slicer",
        category: "kitchen-accessories",
        brand: "other",
        price: 6.99,
        discount: 9.6,
        rating: 2.91,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Egg%20Slicer/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc90",
        title: "Electric Stove",
        category: "kitchen-accessories",
        brand: "other",
        price: 49.99,
        discount: 16.64,
        rating: 4.84,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Electric%20Stove/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc91",
        title: "Fine Mesh Strainer",
        category: "kitchen-accessories",
        brand: "other",
        price: 9.99,
        discount: 2.56,
        rating: 3.7,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Fine%20Mesh%20Strainer/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc92",
        title: "Fork",
        category: "kitchen-accessories",
        brand: "other",
        price: 3.99,
        discount: 14.36,
        rating: 4.18,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Fork/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc93",
        title: "Glass",
        category: "kitchen-accessories",
        brand: "other",
        price: 4.99,
        discount: 7.38,
        rating: 3.06,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Glass/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc94",
        title: "Grater Black",
        category: "kitchen-accessories",
        brand: "other",
        price: 10.99,
        discount: 3.29,
        rating: 2.87,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Grater%20Black/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc95",
        title: "Hand Blender",
        category: "kitchen-accessories",
        brand: "other",
        price: 34.99,
        discount: 6.44,
        rating: 3.71,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Hand%20Blender/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc96",
        title: "Ice Cube Tray",
        category: "kitchen-accessories",
        brand: "other",
        price: 5.99,
        discount: 0.95,
        rating: 3.27,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Ice%20Cube%20Tray/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc97",
        title: "Kitchen Sieve",
        category: "kitchen-accessories",
        brand: "other",
        price: 7.99,
        discount: 9.23,
        rating: 2.96,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Kitchen%20Sieve/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc98",
        title: "Knife",
        category: "kitchen-accessories",
        brand: "other",
        price: 14.99,
        discount: 19.95,
        rating: 4.31,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Knife/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc99",
        title: "Lunch Box",
        category: "kitchen-accessories",
        brand: "other",
        price: 12.99,
        discount: 15.33,
        rating: 2.84,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Lunch%20Box/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc9a",
        title: "Microwave Oven",
        category: "kitchen-accessories",
        brand: "other",
        price: 89.99,
        discount: 18.73,
        rating: 2.71,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Microwave%20Oven/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc9b",
        title: "Mug Tree Stand",
        category: "kitchen-accessories",
        brand: "other",
        price: 15.99,
        discount: 15.21,
        rating: 4.34,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Mug%20Tree%20Stand/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc9c",
        title: "Pan",
        category: "kitchen-accessories",
        brand: "other",
        price: 24.99,
        discount: 6.55,
        rating: 3.4,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Pan/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc9d",
        title: "Plate",
        category: "kitchen-accessories",
        brand: "other",
        price: 3.99,
        discount: 13.03,
        rating: 3.07,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Plate/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc9e",
        title: "Red Tongs",
        category: "kitchen-accessories",
        brand: "other",
        price: 6.99,
        discount: 18.24,
        rating: 3.22,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Red%20Tongs/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdc9f",
        title: "Silver Pot With Glass Cap",
        category: "kitchen-accessories",
        brand: "other",
        price: 39.99,
        discount: 4.57,
        rating: 3.86,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Silver%20Pot%20With%20Glass%20Cap/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdca0",
        title: "Slotted Turner",
        category: "kitchen-accessories",
        brand: "other",
        price: 8.99,
        discount: 7.24,
        rating: 3.77,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Slotted%20Turner/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdca1",
        title: "Spice Rack",
        category: "kitchen-accessories",
        brand: "other",
        price: 19.99,
        discount: 13.78,
        rating: 4.05,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Spice%20Rack/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdca2",
        title: "Spoon",
        category: "kitchen-accessories",
        brand: "other",
        price: 4.99,
        discount: 0.93,
        rating: 3.98,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Spoon/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdca3",
        title: "Tray",
        category: "kitchen-accessories",
        brand: "other",
        price: 16.99,
        discount: 9.93,
        rating: 3.2,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Tray/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdca4",
        title: "Wooden Rolling Pin",
        category: "kitchen-accessories",
        brand: "other",
        price: 11.99,
        discount: 16.94,
        rating: 4.99,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Wooden%20Rolling%20Pin/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdca5",
        title: "Yellow Peeler",
        category: "kitchen-accessories",
        brand: "other",
        price: 5.99,
        discount: 17.09,
        rating: 4.41,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/kitchen-accessories/Yellow%20Peeler/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdca6",
        title: "Apple MacBook Pro 14 Inch Space Grey",
        category: "laptops",
        brand: "Apple",
        price: 1999.99,
        discount: 9.25,
        rating: 3.13,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdca7",
        title: "Asus Zenbook Pro Dual Screen Laptop",
        category: "laptops",
        brand: "Asus",
        price: 1799.99,
        discount: 9.21,
        rating: 3.14,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdca8",
        title: "Huawei Matebook X Pro",
        category: "laptops",
        brand: "Huawei",
        price: 1399.99,
        discount: 15.25,
        rating: 4.62,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdca9",
        title: "Lenovo Yoga 920",
        category: "laptops",
        brand: "Lenovo",
        price: 1099.99,
        discount: 7.77,
        rating: 2.98,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcaa",
        title: "New DELL XPS 13 9300 Laptop",
        category: "laptops",
        brand: "Dell",
        price: 1499.99,
        discount: 11.7,
        rating: 2.98,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcab",
        title: "Blue & Black Check Shirt",
        category: "mens-shirts",
        brand: "Fashion Trends",
        price: 29.99,
        discount: 1.41,
        rating: 4.19,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mens-shirts/Blue%20&%20Black%20Check%20Shirt/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcac",
        title: "Gigabyte Aorus Men Tshirt",
        category: "mens-shirts",
        brand: "Gigabyte",
        price: 24.99,
        discount: 12.6,
        rating: 4.95,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcad",
        title: "Man Plaid Shirt",
        category: "mens-shirts",
        brand: "Classic Wear",
        price: 34.99,
        discount: 17.53,
        rating: 3.66,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mens-shirts/Man%20Plaid%20Shirt/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcae",
        title: "Man Short Sleeve Shirt",
        category: "mens-shirts",
        brand: "Casual Comfort",
        price: 19.99,
        discount: 8.65,
        rating: 4.62,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mens-shirts/Man%20Short%20Sleeve%20Shirt/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcaf",
        title: "Men Check Shirt",
        category: "mens-shirts",
        brand: "Urban Chic",
        price: 27.99,
        discount: 14.21,
        rating: 2.9,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mens-shirts/Men%20Check%20Shirt/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcb0",
        title: "Nike Air Jordan 1 Red And Black",
        category: "mens-shoes",
        brand: "Nike",
        price: 149.99,
        discount: 15.82,
        rating: 2.77,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mens-shoes/Nike%20Air%20Jordan%201%20Red%20And%20Black/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcb1",
        title: "Nike Baseball Cleats",
        category: "mens-shoes",
        brand: "Nike",
        price: 79.99,
        discount: 11.4,
        rating: 4.01,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mens-shoes/Nike%20Baseball%20Cleats/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcb2",
        title: "Puma Future Rider Trainers",
        category: "mens-shoes",
        brand: "Puma",
        price: 89.99,
        discount: 3.64,
        rating: 4.85,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mens-shoes/Puma%20Future%20Rider%20Trainers/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcb3",
        title: "Sports Sneakers Off White & Red",
        category: "mens-shoes",
        brand: "Off White",
        price: 119.99,
        discount: 11.69,
        rating: 4.92,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mens-shoes/Sports%20Sneakers%20Off%20White%20&%20Red/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcb4",
        title: "Sports Sneakers Off White Red",
        category: "mens-shoes",
        brand: "Off White",
        price: 109.99,
        discount: 17.22,
        rating: 2.95,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mens-shoes/Sports%20Sneakers%20Off%20White%20Red/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcb5",
        title: "Brown Leather Belt Watch",
        category: "mens-watches",
        brand: "Fashion Timepieces",
        price: 89.99,
        discount: 15.01,
        rating: 4.47,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcb6",
        title: "Longines Master Collection",
        category: "mens-watches",
        brand: "Longines",
        price: 1499.99,
        discount: 0.64,
        rating: 2.64,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcb7",
        title: "Rolex Cellini Date Black Dial",
        category: "mens-watches",
        brand: "Rolex",
        price: 8999.99,
        discount: 14.28,
        rating: 3.61,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcb8",
        title: "Rolex Cellini Moonphase",
        category: "mens-watches",
        brand: "Rolex",
        price: 12999.99,
        discount: 5.7,
        rating: 4.52,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Moonphase/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcb9",
        title: "Rolex Datejust",
        category: "mens-watches",
        brand: "Rolex",
        price: 10999.99,
        discount: 9.69,
        rating: 4.94,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcba",
        title: "Rolex Submariner Watch",
        category: "mens-watches",
        brand: "Rolex",
        price: 13999.99,
        discount: 0.82,
        rating: 2.97,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcbb",
        title: "Amazon Echo Plus",
        category: "mobile-accessories",
        brand: "Amazon",
        price: 99.99,
        discount: 16.3,
        rating: 3.52,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mobile-accessories/Amazon%20Echo%20Plus/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcbc",
        title: "Apple Airpods",
        category: "mobile-accessories",
        brand: "Apple",
        price: 129.99,
        discount: 4.82,
        rating: 4.38,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Airpods/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcbd",
        title: "Apple AirPods Max Silver",
        category: "mobile-accessories",
        brand: "Apple",
        price: 549.99,
        discount: 11.7,
        rating: 3.11,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20AirPods%20Max%20Silver/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcbe",
        title: "Apple Airpower Wireless Charger",
        category: "mobile-accessories",
        brand: "Apple",
        price: 79.99,
        discount: 6.54,
        rating: 4.51,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Airpower%20Wireless%20Charger/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcbf",
        title: "Apple HomePod Mini Cosmic Grey",
        category: "mobile-accessories",
        brand: "Apple",
        price: 99.99,
        discount: 3.7,
        rating: 4.51,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20HomePod%20Mini%20Cosmic%20Grey/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcc0",
        title: "Apple iPhone Charger",
        category: "mobile-accessories",
        brand: "Apple",
        price: 19.99,
        discount: 1.01,
        rating: 3.03,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20iPhone%20Charger/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcc1",
        title: "Apple MagSafe Battery Pack",
        category: "mobile-accessories",
        brand: "Apple",
        price: 99.99,
        discount: 10.27,
        rating: 2.61,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20MagSafe%20Battery%20Pack/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcc2",
        title: "Apple Watch Series 4 Gold",
        category: "mobile-accessories",
        brand: "Apple",
        price: 349.99,
        discount: 5.14,
        rating: 4.42,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Watch%20Series%204%20Gold/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcc3",
        title: "Beats Flex Wireless Earphones",
        category: "mobile-accessories",
        brand: "Beats",
        price: 49.99,
        discount: 8.27,
        rating: 4.17,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mobile-accessories/Beats%20Flex%20Wireless%20Earphones/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcc4",
        title: "iPhone 12 Silicone Case with MagSafe Plum",
        category: "mobile-accessories",
        brand: "Apple",
        price: 29.99,
        discount: 14.35,
        rating: 4.41,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mobile-accessories/iPhone%2012%20Silicone%20Case%20with%20MagSafe%20Plum/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcc5",
        title: "Monopod",
        category: "mobile-accessories",
        brand: "TechGear",
        price: 19.99,
        discount: 11.62,
        rating: 2.99,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mobile-accessories/Monopod/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcc6",
        title: "Selfie Lamp with iPhone",
        category: "mobile-accessories",
        brand: "GadgetMaster",
        price: 14.99,
        discount: 13.86,
        rating: 2.84,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mobile-accessories/Selfie%20Lamp%20with%20iPhone/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcc7",
        title: "Selfie Stick Monopod",
        category: "mobile-accessories",
        brand: "SnapTech",
        price: 12.99,
        discount: 15.29,
        rating: 2.93,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mobile-accessories/Selfie%20Stick%20Monopod/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcc8",
        title: "TV Studio Camera Pedestal",
        category: "mobile-accessories",
        brand: "ProVision",
        price: 499.99,
        discount: 10.28,
        rating: 4.05,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/mobile-accessories/TV%20Studio%20Camera%20Pedestal/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcc9",
        title: "Generic Motorcycle",
        category: "motorcycle",
        brand: "Generic Motors",
        price: 3999.99,
        discount: 2.89,
        rating: 4.85,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/motorcycle/Generic%20Motorcycle/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcca",
        title: "Kawasaki Z800",
        category: "motorcycle",
        brand: "Kawasaki",
        price: 8999.99,
        discount: 15.07,
        rating: 4.06,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/motorcycle/Kawasaki%20Z800/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdccb",
        title: "MotoGP CI.H1",
        category: "motorcycle",
        brand: "MotoGP",
        price: 14999.99,
        discount: 17,
        rating: 4.15,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/motorcycle/MotoGP%20CI.H1/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdccc",
        title: "Scooter Motorcycle",
        category: "motorcycle",
        brand: "ScootMaster",
        price: 2999.99,
        discount: 19.19,
        rating: 3.33,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/motorcycle/Scooter%20Motorcycle/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdccd",
        title: "Sportbike Motorcycle",
        category: "motorcycle",
        brand: "SpeedMaster",
        price: 7499.99,
        discount: 18.07,
        rating: 2.97,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/motorcycle/Sportbike%20Motorcycle/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcce",
        title: "Attitude Super Leaves Hand Soap",
        category: "skin-care",
        brand: "Attitude",
        price: 8.99,
        discount: 17.42,
        rating: 4.68,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/skin-care/Attitude%20Super%20Leaves%20Hand%20Soap/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdccf",
        title: "Olay Ultra Moisture Shea Butter Body Wash",
        category: "skin-care",
        brand: "Olay",
        price: 12.99,
        discount: 16.95,
        rating: 4.81,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/skin-care/Olay%20Ultra%20Moisture%20Shea%20Butter%20Body%20Wash/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcd0",
        title: "Vaseline Men Body and Face Lotion",
        category: "skin-care",
        brand: "Vaseline",
        price: 9.99,
        discount: 11.63,
        rating: 3.97,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/skin-care/Vaseline%20Men%20Body%20and%20Face%20Lotion/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcd1",
        title: "iPhone 5s",
        category: "smartphones",
        brand: "Apple",
        price: 199.99,
        discount: 11.85,
        rating: 3.92,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcd2",
        title: "iPhone 6",
        category: "smartphones",
        brand: "Apple",
        price: 299.99,
        discount: 4.54,
        rating: 3.76,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcd3",
        title: "iPhone 13 Pro",
        category: "smartphones",
        brand: "Apple",
        price: 1099.99,
        discount: 18.3,
        rating: 3.42,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcd4",
        title: "iPhone X",
        category: "smartphones",
        brand: "Apple",
        price: 899.99,
        discount: 14.19,
        rating: 4.96,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcd5",
        title: "Oppo A57",
        category: "smartphones",
        brand: "Oppo",
        price: 249.99,
        discount: 12.17,
        rating: 3.1,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20A57/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcd6",
        title: "Oppo F19 Pro Plus",
        category: "smartphones",
        brand: "Oppo",
        price: 399.99,
        discount: 15.62,
        rating: 2.57,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcd7",
        title: "Oppo K1",
        category: "smartphones",
        brand: "Oppo",
        price: 299.99,
        discount: 14.58,
        rating: 3.39,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcd8",
        title: "Realme C35",
        category: "smartphones",
        brand: "Realme",
        price: 149.99,
        discount: 16.47,
        rating: 2.56,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/smartphones/Realme%20C35/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcd9",
        title: "Realme X",
        category: "smartphones",
        brand: "Realme",
        price: 299.99,
        discount: 2.39,
        rating: 4.42,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/smartphones/Realme%20X/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcda",
        title: "Realme XT",
        category: "smartphones",
        brand: "Realme",
        price: 349.99,
        discount: 3.03,
        rating: 4.14,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/smartphones/Realme%20XT/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcdb",
        title: "Samsung Galaxy S7",
        category: "smartphones",
        brand: "Samsung",
        price: 299.99,
        discount: 8.83,
        rating: 4.9,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S7/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcdc",
        title: "Samsung Galaxy S8",
        category: "smartphones",
        brand: "Samsung",
        price: 499.99,
        discount: 2.69,
        rating: 3.69,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S8/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcdd",
        title: "Samsung Galaxy S10",
        category: "smartphones",
        brand: "Samsung",
        price: 699.99,
        discount: 0.97,
        rating: 2.81,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S10/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcde",
        title: "Vivo S1",
        category: "smartphones",
        brand: "Vivo",
        price: 249.99,
        discount: 4.25,
        rating: 2.83,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20S1/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcdf",
        title: "Vivo V9",
        category: "smartphones",
        brand: "Vivo",
        price: 299.99,
        discount: 14.57,
        rating: 3.1,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20V9/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdce0",
        title: "Vivo X21",
        category: "smartphones",
        brand: "Vivo",
        price: 499.99,
        discount: 7.32,
        rating: 2.75,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20X21/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdce1",
        title: "American Football",
        category: "sports-accessories",
        brand: "other",
        price: 19.99,
        discount: 10.28,
        rating: 3.78,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/American%20Football/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdce2",
        title: "Baseball Ball",
        category: "sports-accessories",
        brand: "other",
        price: 8.99,
        discount: 13.72,
        rating: 4.76,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/Baseball%20Ball/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdce3",
        title: "Baseball Glove",
        category: "sports-accessories",
        brand: "other",
        price: 24.99,
        discount: 16.27,
        rating: 2.72,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/Baseball%20Glove/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdce4",
        title: "Basketball",
        category: "sports-accessories",
        brand: "other",
        price: 14.99,
        discount: 18.05,
        rating: 4.15,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/Basketball/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdce5",
        title: "Basketball Rim",
        category: "sports-accessories",
        brand: "other",
        price: 39.99,
        discount: 6.02,
        rating: 4.98,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/Basketball%20Rim/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdce6",
        title: "Cricket Ball",
        category: "sports-accessories",
        brand: "other",
        price: 12.99,
        discount: 12.93,
        rating: 4.43,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/Cricket%20Ball/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdce7",
        title: "Cricket Bat",
        category: "sports-accessories",
        brand: "other",
        price: 29.99,
        discount: 9.03,
        rating: 3.07,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/Cricket%20Bat/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdce8",
        title: "Cricket Helmet",
        category: "sports-accessories",
        brand: "other",
        price: 44.99,
        discount: 10.75,
        rating: 3.34,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/Cricket%20Helmet/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdce9",
        title: "Cricket Wicket",
        category: "sports-accessories",
        brand: "other",
        price: 29.99,
        discount: 8.79,
        rating: 4.16,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/Cricket%20Wicket/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcea",
        title: "Feather Shuttlecock",
        category: "sports-accessories",
        brand: "other",
        price: 5.99,
        discount: 10.24,
        rating: 3.95,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/Feather%20Shuttlecock/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdceb",
        title: "Football",
        category: "sports-accessories",
        brand: "other",
        price: 17.99,
        discount: 0.59,
        rating: 3.94,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/Football/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcec",
        title: "Golf Ball",
        category: "sports-accessories",
        brand: "other",
        price: 9.99,
        discount: 19.38,
        rating: 4.84,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/Golf%20Ball/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdced",
        title: "Iron Golf",
        category: "sports-accessories",
        brand: "other",
        price: 49.99,
        discount: 3.32,
        rating: 4.87,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/Iron%20Golf/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcee",
        title: "Metal Baseball Bat",
        category: "sports-accessories",
        brand: "other",
        price: 29.99,
        discount: 2.55,
        rating: 4.11,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/Metal%20Baseball%20Bat/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcef",
        title: "Tennis Ball",
        category: "sports-accessories",
        brand: "other",
        price: 6.99,
        discount: 0.14,
        rating: 4.77,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/Tennis%20Ball/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcf0",
        title: "Tennis Racket",
        category: "sports-accessories",
        brand: "other",
        price: 49.99,
        discount: 15.8,
        rating: 3.82,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/Tennis%20Racket/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcf1",
        title: "Volleyball",
        category: "sports-accessories",
        brand: "other",
        price: 11.99,
        discount: 2.2,
        rating: 4.08,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sports-accessories/Volleyball/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcf2",
        title: "Black Sun Glasses",
        category: "sunglasses",
        brand: "Fashion Shades",
        price: 29.99,
        discount: 14.22,
        rating: 3.23,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sunglasses/Black%20Sun%20Glasses/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcf3",
        title: "Classic Sun Glasses",
        category: "sunglasses",
        brand: "Fashion Shades",
        price: 24.99,
        discount: 15.67,
        rating: 2.99,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sunglasses/Classic%20Sun%20Glasses/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcf4",
        title: "Green and Black Glasses",
        category: "sunglasses",
        brand: "Fashion Shades",
        price: 34.99,
        discount: 10.75,
        rating: 2.84,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sunglasses/Green%20and%20Black%20Glasses/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcf5",
        title: "Party Glasses",
        category: "sunglasses",
        brand: "Fashion Fun",
        price: 19.99,
        discount: 19.52,
        rating: 3.21,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sunglasses/Party%20Glasses/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcf6",
        title: "Sunglasses",
        category: "sunglasses",
        brand: "Fashion Shades",
        price: 22.99,
        discount: 4.87,
        rating: 2.58,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/sunglasses/Sunglasses/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcf7",
        title: "iPad Mini 2021 Starlight",
        category: "tablets",
        brand: "Apple",
        price: 499.99,
        discount: 19.48,
        rating: 3.87,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/tablets/iPad%20Mini%202021%20Starlight/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcf8",
        title: "Samsung Galaxy Tab S8 Plus Grey",
        category: "tablets",
        brand: "Samsung",
        price: 599.99,
        discount: 8.11,
        rating: 3.43,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20S8%20Plus%20Grey/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcf9",
        title: "Samsung Galaxy Tab White",
        category: "tablets",
        brand: "Samsung",
        price: 349.99,
        discount: 4.82,
        rating: 3.7,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20White/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcfa",
        title: "Blue Frock",
        category: "tops",
        brand: "other",
        price: 29.99,
        discount: 9.37,
        rating: 3.57,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/tops/Blue%20Frock/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcfb",
        title: "Girl Summer Dress",
        category: "tops",
        brand: "other",
        price: 19.99,
        discount: 6.42,
        rating: 2.67,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/tops/Girl%20Summer%20Dress/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcfc",
        title: "Gray Dress",
        category: "tops",
        brand: "other",
        price: 34.99,
        discount: 9.32,
        rating: 3.49,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/tops/Gray%20Dress/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcfd",
        title: "Short Frock",
        category: "tops",
        brand: "other",
        price: 24.99,
        discount: 9.47,
        rating: 4.63,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/tops/Short%20Frock/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcfe",
        title: "Tartan Dress",
        category: "tops",
        brand: "other",
        price: 39.99,
        discount: 2.08,
        rating: 2.82,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/tops/Tartan%20Dress/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdcff",
        title: "300 Touring",
        category: "vehicle",
        brand: "Chrysler",
        price: 28999.99,
        discount: 7.15,
        rating: 4.56,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/vehicle/300%20Touring/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd00",
        title: "Charger SXT RWD",
        category: "vehicle",
        brand: "Dodge",
        price: 32999.99,
        discount: 2.27,
        rating: 2.92,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/vehicle/Charger%20SXT%20RWD/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd01",
        title: "Dodge Hornet GT Plus",
        category: "vehicle",
        brand: "Dodge",
        price: 24999.99,
        discount: 14.26,
        rating: 3.93,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/vehicle/Dodge%20Hornet%20GT%20Plus/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd02",
        title: "Durango SXT RWD",
        category: "vehicle",
        brand: "Dodge",
        price: 36999.99,
        discount: 9.21,
        rating: 3.47,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/vehicle/Durango%20SXT%20RWD/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd03",
        title: "Pacifica Touring",
        category: "vehicle",
        brand: "Chrysler",
        price: 31999.99,
        discount: 6.89,
        rating: 2.96,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/vehicle/Pacifica%20Touring/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd04",
        title: "Blue Women's Handbag",
        category: "womens-bags",
        brand: "Fashionista",
        price: 49.99,
        discount: 5.24,
        rating: 3.37,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-bags/Blue%20Women's%20Handbag/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd05",
        title: "Heshe Women's Leather Bag",
        category: "womens-bags",
        brand: "Heshe",
        price: 129.99,
        discount: 7.74,
        rating: 2.62,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-bags/Heshe%20Women's%20Leather%20Bag/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd06",
        title: "Prada Women Bag",
        category: "womens-bags",
        brand: "Prada",
        price: 599.99,
        discount: 18.3,
        rating: 3.52,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-bags/Prada%20Women%20Bag/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd07",
        title: "White Faux Leather Backpack",
        category: "womens-bags",
        brand: "Urban Chic",
        price: 39.99,
        discount: 7.76,
        rating: 4.91,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-bags/White%20Faux%20Leather%20Backpack/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd08",
        title: "Women Handbag Black",
        category: "womens-bags",
        brand: "Elegance Collection",
        price: 59.99,
        discount: 3.08,
        rating: 4.94,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-bags/Women%20Handbag%20Black/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd09",
        title: "Black Women's Gown",
        category: "womens-dresses",
        brand: "other",
        price: 129.99,
        discount: 5.86,
        rating: 4.77,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-dresses/Black%20Women's%20Gown/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd0a",
        title: "Corset Leather With Skirt",
        category: "womens-dresses",
        brand: "other",
        price: 89.99,
        discount: 19.26,
        rating: 2.52,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-dresses/Corset%20Leather%20With%20Skirt/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd0b",
        title: "Corset With Black Skirt",
        category: "womens-dresses",
        brand: "other",
        price: 79.99,
        discount: 14.61,
        rating: 3,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-dresses/Corset%20With%20Black%20Skirt/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd0c",
        title: "Dress Pea",
        category: "womens-dresses",
        brand: "other",
        price: 49.99,
        discount: 9.81,
        rating: 2.92,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-dresses/Dress%20Pea/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd0d",
        title: "Marni Red & Black Suit",
        category: "womens-dresses",
        brand: "other",
        price: 179.99,
        discount: 15.4,
        rating: 4.17,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-dresses/Marni%20Red%20&%20Black%20Suit/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd0e",
        title: "Green Crystal Earring",
        category: "womens-jewellery",
        brand: "other",
        price: 29.99,
        discount: 2.58,
        rating: 2.94,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-jewellery/Green%20Crystal%20Earring/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd0f",
        title: "Green Oval Earring",
        category: "womens-jewellery",
        brand: "other",
        price: 24.99,
        discount: 0.64,
        rating: 2.54,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-jewellery/Green%20Oval%20Earring/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd10",
        title: "Tropical Earring",
        category: "womens-jewellery",
        brand: "other",
        price: 19.99,
        discount: 12.31,
        rating: 3.32,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-jewellery/Tropical%20Earring/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd11",
        title: "Black & Brown Slipper",
        category: "womens-shoes",
        brand: "Comfort Trends",
        price: 19.99,
        discount: 13.62,
        rating: 4.13,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-shoes/Black%20&%20Brown%20Slipper/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd12",
        title: "Calvin Klein Heel Shoes",
        category: "womens-shoes",
        brand: "Calvin Klein",
        price: 79.99,
        discount: 11.39,
        rating: 4.06,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-shoes/Calvin%20Klein%20Heel%20Shoes/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd13",
        title: "Golden Shoes Woman",
        category: "womens-shoes",
        brand: "Fashion Diva",
        price: 49.99,
        discount: 14.93,
        rating: 4.82,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-shoes/Golden%20Shoes%20Woman/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd14",
        title: "Pampi Shoes",
        category: "womens-shoes",
        brand: "Pampi",
        price: 29.99,
        discount: 0.3,
        rating: 3.01,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-shoes/Pampi%20Shoes/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd15",
        title: "Red Shoes",
        category: "womens-shoes",
        brand: "Fashion Express",
        price: 34.99,
        discount: 0.01,
        rating: 4.23,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-shoes/Red%20Shoes/thumbnail.png",
    },
    {
        _id: "66b5befb311c2c34503fdd16",
        title: "IWC Ingenieur Automatic Steel",
        category: "womens-watches",
        brand: "IWC",
        price: 4999.99,
        discount: 5.76,
        rating: 2.58,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/womens-watches/IWC%20Ingenieur%20Automatic%20Steel/thumbnail.png",
    },
];

export const filterCategory = [...new Set(data.map((i) => i.category))].map(
    (i) => ({
        title: i,
        description: "this is a description " + i,
        thumbnail:
            "https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/thumbnail.png",
    })
);
export const filterBrand = [...new Set(data.map((i) => i.brand))].map((i) => ({
    title: i,
    description: "this is a brand " + i,
    thumbnail:
        "https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/thumbnail.png",
}));
